### ISSUE TITLE
Service annotations do not work for deployments

### ISSUE THREAD

**Issue by gvfnix** [gvfnix/shapeshifter-helm-chart#7]
Values:
```
    deployments:
      data-migration-kowl:
        pod:
          containers:
            app:
              args:
              - --config.filepath=/mnt/config/main.yml
              image:
                repository: quay.io/cloudhut/kowl
                tag: v1.5.0
              mounts:
                /mnt/config:
                  volume: config
              ports:
                http:
                  containerPort: 8080
          volumes:
            config:
              configMap:
                name: data-migration-kowl
        service:
          enable: true
          metadata:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: data-migration-kowl.example.org
```

Actual service:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: data-migration-kowl
    meta.helm.sh/release-namespace: kafka
  creationTimestamp: "2023-03-07T15:44:34Z"
```
